import{state,clamp}from'./state.js';
export function createAudio(){if(state.audio)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ac=new AC,master=ac.createGain();master.gain.value=.0001;master.connect(ac.destination);
const engine=ac.createOscillator(),engineGain=ac.createGain(),engineFilter=ac.createBiquadFilter();engine.type='sawtooth';engine.frequency.value=72;engineGain.gain.value=.16;engineFilter.type='lowpass';engineFilter.frequency.value=620;engine.connect(engineFilter).connect(engineGain).connect(master);engine.start();
const sub=ac.createOscillator(),subGain=ac.createGain();sub.type='triangle';sub.frequency.value=38;subGain.gain.value=.08;sub.connect(subGain).connect(master);sub.start();
const buffer=ac.createBuffer(1,ac.sampleRate*2,ac.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;
const wind=ac.createBufferSource(),windFilter=ac.createBiquadFilter(),windGain=ac.createGain();wind.buffer=buffer;wind.loop=true;windFilter.type='highpass';windFilter.frequency.value=900;windGain.gain.value=.001;wind.connect(windFilter).connect(windGain).connect(master);wind.start();
const road=ac.createBufferSource(),roadFilter=ac.createBiquadFilter(),roadGain=ac.createGain();road.buffer=buffer;road.loop=true;roadFilter.type='bandpass';roadFilter.frequency.value=170;roadFilter.Q.value=.7;roadGain.gain.value=.001;road.connect(roadFilter).connect(roadGain).connect(master);road.start();state.audio={ac,master,engine,engineGain,engineFilter,sub,subGain,windFilter,windGain,roadFilter,roadGain}}
export function toggleAudio(button){state.sound=!state.sound;button.textContent=state.sound?'♫':'♪';if(state.sound){createAudio();if(state.audio?.ac.state==='suspended')state.audio.ac.resume()}else if(state.audio)state.audio.master.gain.setTargetAtTime(.0001,state.audio.ac.currentTime,.06)}
export function stopAudio(button){state.sound=false;if(button)button.textContent='♪';if(state.audio){try{state.audio.ac.close()}catch{}state.audio=null}}
export function updateAudio(){if(!state.sound||!state.audio)return;const{ac,master,engine,engineGain,engineFilter,sub,subGain,windFilter,windGain,roadFilter,roadGain}=state.audio,sn=clamp(state.speed/138,0,1);master.gain.setTargetAtTime(.06,ac.currentTime,.14);engine.frequency.setTargetAtTime(62+state.speed*.92,ac.currentTime,.055);engineFilter.frequency.setTargetAtTime(480+state.speed*9.5,ac.currentTime,.08);engineGain.gain.setTargetAtTime(.11+sn*.12,ac.currentTime,.1);sub.frequency.setTargetAtTime(34+state.speed*.28,ac.currentTime,.08);subGain.gain.setTargetAtTime(.045+sn*.035,ac.currentTime,.1);windFilter.frequency.setTargetAtTime(760+state.speed*17,ac.currentTime,.08);windGain.gain.setTargetAtTime(.006+Math.pow(sn,1.7)*.17,ac.currentTime,.12);roadFilter.frequency.setTargetAtTime(120+state.speed*1.8,ac.currentTime,.1);roadGain.gain.setTargetAtTime(.014+sn*.09,ac.currentTime,.12)}
