import{state,ENVS,ENV_LABELS,clamp,lerp,hash}from'./state.js';
import{updateAudio}from'./audio.js';
import{drawSky,drawFarEnvironment}from'./render-bg.js';
import{drawRoad}from'./road-surface.js';
import{drawRoadside}from'./roadside.js';
import{drawFeature,drawWeather,drawCockpit}from'./render-effects.js';
import{initControls}from'./controls.js';
import{ui,updateHud,toast}from'./ui.js';
const canvas=document.getElementById('driveCanvas'),ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
function resize(){const r=canvas.getBoundingClientRect();state.dpr=Math.min(devicePixelRatio||1,2);state.width=Math.max(1,r.width);state.height=Math.max(1,r.height);canvas.width=Math.round(state.width*state.dpr);canvas.height=Math.round(state.height*state.dpr);ctx.setTransform(state.dpr,0,0,state.dpr,0,0);ctx.imageSmoothingEnabled=true}
function update(dt){if(!state.running||state.paused)return;state.speed=lerp(state.speed,state.targetSpeed,1-Math.exp(-dt*1.8));const sn=state.speed/100;state.distance+=state.speed*dt*.88;state.roadPhase=(state.roadPhase+state.speed*dt*1.7)%10000;const raw=state.control==='tilt'?state.tiltSteer:state.buttonSteer;state.steer=lerp(state.steer,raw,1-Math.exp(-dt*8));state.lateral=clamp((state.lateral+state.steer*dt*(.6+sn*.46))*Math.pow(.988,dt*60),-.72,.72);if(state.endless){const next=(state.routeOrigin+Math.floor(state.distance/2600))%ENVS.length;if(next!==state.envIndex){state.envIndex=next;state.environment=ENVS[next];toast(`${ENV_LABELS[state.environment]} へ景色が変化`)}}state.featureCooldown-=dt;if(!state.feature&&state.featureCooldown<=0){const cycle=Math.floor(state.distance/700);if(cycle>0&&(cycle%6===2||cycle%6===4)){state.feature=cycle%6===2?'tunnel':'bridge';state.featureProgress=0}}if(state.feature){state.featureProgress+=dt*(.12+sn*.08);if(state.featureProgress>=1){state.feature=null;state.featureCooldown=14+hash(Math.floor(state.distance))*12}}updateAudio();updateHud()}
function draw(){const w=state.width,h=state.height;if(!w||!h)return;const hor=h*(.34-clamp(state.speed/120,0,1.3)*.018);ctx.save();const shake=state.running?clamp((state.speed-105)/90,0,1)*.65:0;if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawSky(ctx,w,h,hor);drawFarEnvironment(ctx,w,h,hor);drawRoad(ctx,w,h,hor);drawRoadside(ctx,w,h,hor);drawFeature(ctx,w,h,hor);drawWeather(ctx,w,h,hor);drawCockpit(ctx,w,h);ctx.restore();if(!state.running){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'rgba(0,0,0,.04)');g.addColorStop(1,'rgba(0,0,0,.22)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}}
function frame(t){const dt=Math.min(.05,Math.max(.001,(t-state.lastT)/1000));state.lastT=t;state.fpsSmoother=lerp(state.fpsSmoother,1/dt,.05);update(dt);draw();requestAnimationFrame(frame)}
addEventListener('resize',resize,{passive:true});addEventListener('orientationchange',()=>setTimeout(resize,120));document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running&&!state.paused){state.paused=true;ui.pauseOverlay.classList.remove('is-hidden')}state.lastT=performance.now()});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(err=>console.warn('[ZenDrive] SW',err)));resize();initControls();draw();requestAnimationFrame(frame);
