import{state,ENVS,ENV_LABELS,clamp,lerp,hash,roadCurveAt}from'./state.js';
import{updateAudio}from'./audio.js';
import{drawSky,drawFarEnvironment}from'./render-bg.js';
import{drawRoad}from'./road-surface.js';
import{drawRoadside}from'./roadside.js';
import{drawFeature,drawWeather,drawCockpit}from'./render-effects.js';
import{initControls}from'./controls.js';
import{ui,updateHud,toast}from'./ui.js';
const skin=document.createElement('link');skin.rel='stylesheet';skin.href='/jdm.css';document.head.appendChild(skin);
const canvas=document.getElementById('driveCanvas'),ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
function resize(){const r=canvas.getBoundingClientRect();state.dpr=Math.min(devicePixelRatio||1,2);state.width=Math.max(1,r.width);state.height=Math.max(1,r.height);canvas.width=Math.round(state.width*state.dpr);canvas.height=Math.round(state.height*state.dpr);ctx.setTransform(state.dpr,0,0,state.dpr,0,0);ctx.imageSmoothingEnabled=true}
function update(dt){if(!state.running||state.paused)return;state.speed=lerp(state.speed,state.targetSpeed,1-Math.exp(-dt*1.8));const sn=state.speed/138;state.distance+=state.speed*dt*.9;state.roadPhase=(state.roadPhase+state.speed*dt*1.95)%10000;const raw=state.control==='tilt'?state.tiltSteer:state.buttonSteer;state.steer=lerp(state.steer,raw,1-Math.exp(-dt*8));state.lateral=clamp((state.lateral+state.steer*dt*(.55+sn*.62))*Math.pow(.988,dt*60),-.72,.72);const curve=roadCurveAt(70);state.roadYaw=lerp(state.roadYaw,curve,1-Math.exp(-dt*5.2));const carTarget=state.steer*.42+curve*.17;state.carYaw=lerp(state.carYaw,carTarget,1-Math.exp(-dt*4.3));const camTarget=state.carYaw*.54+curve*.08;state.cameraYaw=lerp(state.cameraYaw,camTarget,1-Math.exp(-dt*2.7));const rollTarget=clamp(-(state.steer*.022+curve*.012)*(.45+sn),-.045,.045);state.cameraRoll=lerp(state.cameraRoll,rollTarget,1-Math.exp(-dt*3.2));const roadBuzz=Math.sin(state.roadPhase*.09)*(.22+sn*.72)+Math.sin(state.roadPhase*.037)*(.16+sn*.4);state.cameraBob=lerp(state.cameraBob,roadBuzz,1-Math.exp(-dt*10));state.speedPulse=lerp(state.speedPulse,clamp((state.speed-75)/63,0,1),1-Math.exp(-dt*2.5));if(Math.floor(state.distance/480)!==Math.floor((state.distance-state.speed*dt*.9)/480)&&hash(Math.floor(state.distance/480))>.62)state.suspensionKick=2.8+sn*2.4;state.suspensionKick=lerp(state.suspensionKick,0,1-Math.exp(-dt*8));if(state.endless){const next=(state.routeOrigin+Math.floor(state.distance/2600))%ENVS.length;if(next!==state.envIndex){state.envIndex=next;state.environment=ENVS[next];toast(`${ENV_LABELS[state.environment]} へ景色が変化`)}}state.featureCooldown-=dt;if(!state.feature&&state.featureCooldown<=0){const cycle=Math.floor(state.distance/700);if(cycle>0&&(cycle%6===2||cycle%6===4)){state.feature=cycle%6===2?'tunnel':'bridge';state.featureProgress=0}}if(state.feature){state.featureProgress+=dt*(.12+sn*.08);if(state.featureProgress>=1){state.feature=null;state.featureCooldown=14+hash(Math.floor(state.distance))*12}}updateAudio();updateHud()}
function draw(){const w=state.width,h=state.height;if(!w||!h)return;const sn=clamp(state.speed/138,0,1),hor=h*(.345-sn*.034);ctx.save();ctx.translate(w*.5,h*.56);ctx.rotate(state.cameraRoll);ctx.translate(-w*.5,-h*.56+state.cameraBob+state.suspensionKick);const shake=state.running?state.speedPulse*.55:0;if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawSky(ctx,w,h,hor);drawFarEnvironment(ctx,w,h,hor);drawRoad(ctx,w,h,hor);drawRoadside(ctx,w,h,hor);drawFeature(ctx,w,h,hor);drawWeather(ctx,w,h,hor);drawCockpit(ctx,w,h);ctx.restore();if(!state.running){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'rgba(0,0,0,.04)');g.addColorStop(1,'rgba(0,0,0,.22)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}}
function frame(t){const dt=Math.min(.05,Math.max(.001,(t-state.lastT)/1000));state.lastT=t;state.fpsSmoother=lerp(state.fpsSmoother,1/dt,.05);update(dt);draw();requestAnimationFrame(frame)}
addEventListener('resize',resize,{passive:true});addEventListener('orientationchange',()=>setTimeout(resize,120));document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running&&!state.paused){state.paused=true;ui.pauseOverlay.classList.remove('is-hidden')}state.lastT=performance.now()});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(err=>console.warn('[ZenDrive] SW',err)));resize();initControls();draw();requestAnimationFrame(frame);
