import{state,ENVS,ENV_LABELS,WEATHER_LABELS,clamp}from'./state.js';
const $=id=>document.getElementById(id);
export const ui={startScreen:$('startScreen'),hud:$('hud'),startBtn:$('startBtn'),startBtnTitle:$('startBtnTitle'),startBtnHint:$('startBtnHint'),permissionNote:$('permissionNote'),speedValue:$('speedValue'),environmentLabel:$('environmentLabel'),weatherLabel:$('weatherLabel'),pauseBtn:$('pauseBtn'),resetBtn:$('resetBtn'),pauseOverlay:$('pauseOverlay'),resumeBtn:$('resumeBtn'),backToMenuBtn:$('backToMenuBtn'),leftBtn:$('leftBtn'),rightBtn:$('rightBtn'),steerButtons:$('steerButtons'),controlToggleBtn:$('controlToggleBtn'),recenterBtn:$('recenterBtn'),modePill:$('modePill'),speedDownBtn:$('speedDownBtn'),speedUpBtn:$('speedUpBtn'),soundBtn:$('soundBtn'),endlessToggle:$('endlessToggle'),toast:$('toast')};
export function updateStartCopy(){if(state.control==='tilt'){ui.startBtnTitle.textContent='傾きを許可してスタート';ui.startBtnHint.textContent='iPhoneは初回のみセンサー許可が必要です'}else{ui.startBtnTitle.textContent='ボタン操作でスタート';ui.startBtnHint.textContent='画面下の ◀ ▶ でステアリング'}}
export function updateControlUI(){const tilt=state.control==='tilt';ui.steerButtons.classList.toggle('is-hidden',tilt);ui.modePill.textContent=tilt?'TILT':'BUTTON';ui.controlToggleBtn.textContent=tilt?'BUTTON':'TILT'}
export function updateHud(){ui.speedValue.textContent=Math.round(state.speed);ui.environmentLabel.textContent=ENV_LABELS[state.environment];ui.weatherLabel.textContent=WEATHER_LABELS[state.weather]}
export function toast(message){ui.toast.textContent=message;ui.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>ui.toast.classList.remove('show'),2200)}
export async function requestTilt(){try{if(typeof DeviceOrientationEvent==='undefined'){state.sensorPermission='unsupported';return false}if(typeof DeviceOrientationEvent.requestPermission==='function'){const r=await DeviceOrientationEvent.requestPermission();state.sensorPermission=r;return r==='granted'}state.sensorPermission='granted';return true}catch(err){console.warn('[ZenDrive] orientation permission failed',err);state.sensorPermission='denied';return false}}
export function startOrientation(){addEventListener('deviceorientation',e=>{if(!state.running||state.control!=='tilt'||typeof e.gamma!=='number')return;const g=clamp(e.gamma,-45,45);if(state.tiltZero===null)state.tiltZero=g;state.tiltSteer=clamp(clamp(g-state.tiltZero,-28,28)/18,-1,1);state.sensorAvailable=true},true)}
export function bindSettings(){document.querySelectorAll('.segmented').forEach(group=>group.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;const key=group.dataset.setting,n=key==='weather-extra'?'weather':key;document.querySelectorAll(`[data-setting="${n}"] button, [data-setting="${n}-extra"] button`).forEach(b=>b.classList.remove('active'));btn.classList.add('active');state[n]=btn.dataset.value;if(n==='environment')state.envIndex=Math.max(0,ENVS.indexOf(state.environment));if(n==='control'){updateControlUI();updateStartCopy()}}));ui.endlessToggle.addEventListener('change',()=>state.endless=ui.endlessToggle.checked)}
